//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockServiceHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrder
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public double StockValue { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string RequestDate { get; set; }
        public string ExecutionDate { get; set; }
    
        public virtual OrderType Type { get; set; }
    }
}
